# Use Node image
FROM node:18

# Working directory
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy frontend source
COPY frontend/ .

# Expose Vite dev port
EXPOSE 5173

# Start React dev server
CMD ["npm", "run", "dev"]